add_newline = false

[battery]
full_symbol = " ðŸ”‹"
charging_symbol = " ðŸ”Œ"
discharging_symbol = " âš¡"

[[battery.display]]
threshold = 99
style = "bold green"

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold green"
always_show_remote = true
only_attached = true

[git_commit]
commit_hash_length = 8
style = "bold white"

[nodejs]
disabled = true

[line_break]
disabled = true

[directory]
truncate_to_repo = true
format = "[$path]($style)"
style = "bold green"
truncation_length = 1
fish_style_pwd_dir_length = 1
repo_root_format= "[$repo_root]($style)[$path]($style)"
